# Generated by Django 6.1 on 2026-08-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor')], default='PATIENT', max_length=10),
        ),
    ]
